server:
  port: 8089

feign:
  hystrix:
    enabled: true
      
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    #hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
    instanceId: microservicea:${spring.application.instance-id:${random.value}}
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
      metadata-map:
        zone: primary # This is needed for the load balancer
        profile: ${spring.profiles.active}
        version: ${info.project.version:}
        git-version: ${git.commit.id.describe:}
        git-commit: ${git.commit.id.abbrev:}
        git-branch: ${git.branch:}


#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
