server:
  port: 8080

feign:
  hystrix:
    enabled: true
     
eureka:
  client:
    enabled: true
    serviceUrl:

      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka.yeseer.cn/eureka/}
  instance:
    #hostname: ${HOSTNAME:localhost}
    preferIpAddress: false

#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
