server:
  port: 8089

feign:
  hystrix:
    enabled: true
      
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    #hostname: ${HOSTNAME:localhost}
    preferIpAddress: false

#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
