server:
  port: 8089

feign:
  hystrix:
    enabled: true
      
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    #hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10



#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
